"use strict";
exports.__esModule = true;
var Example_1 = require("./Usage/Example");
var exampleLinkedList = new Example_1.ExampleLinkedList();
// exampleLinkedList.push();
exampleLinkedList.insertAfter();
exampleLinkedList.nodeAt(1);
// exampleLinkedList.pop();
// exampleLinkedList.removeLast();
// exampleLinkedList.removeAfter(0);
// exampleLinkedList.size();
